all: help.exe strlength.exe strconcat.exe strcompare.exe

help.exe:	zad1.c
	gcc zad1.c -o help.exe
	
mystrings.exe:	mystrings.c
	gcc mystrings.c -o mystrings.exe

strlength.exe:	strlength.c
	gcc strlength.c -o strlength.exe

strconcat.exe: 	strconcat.c
	gcc strconcat.c -o strconcat.exe

strcompare.exe: strcompare.c
	gcc strcompare.c -o strcompare.exe

clean:
	rm -f *.exe